name: Scorecard

on:
  workflow_dispatch:
  branch_protection_rule:
    types:
      - created
      - edited
      - deleted
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  run-scorecard:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
      repository-projects: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true